services:
  - type: web
    name: php-app
    env: php
    plan: free
    buildCommand: "" # Pas de commande de build pour PHP
    startCommand: php -S 0.0.0.0:10000 -t public # ou ./ si les fichiers PHP sont à la racine
    envVars:
      - key: RENDER_PHP_VERSION
        value: 8.2 # Remplacez par la version PHP nécessaire
